import type { Chronicle } from '../../src/engine/story';

export const BloodGamesChronicle: Chronicle = {
  id: 'blood-games',
  title: 'Blood Games',
  subtitle: 'A Sabbat Trial of Fire',
  setting: 'Chicago, 1997',
  era: 'modern',
  acts: {
    1: 'The Vaulderie',
    2: 'Trial by Combat',
    3: 'Aftermath',
  },
  npcs: {},
  endings: {
    victory_easy: {
      type: 'good_end',
      title: 'Proven Worthy',
      text: "Rodrigo falls to the cold stone, broken but not destroyed. The pack cheers. You have passed the first trial of the Vaulderie — your blood mixed with theirs, your worth proven by fang and fist. In the Sabbat, respect is earned in blood. Tonight, you earned yours.",
    },
    victory_medium: {
      type: 'good_end',
      title: 'Above the Pack',
      text: "Three Sabbat vampires lie broken around you. The gathered sect watches in silence, then erupts in howls of acclaim. Even Zeta, half-reverted, manages a grin through shattered fangs. The Archbishop nods once from across the room. You are Sabbat.",
    },
    victory_hard: {
      type: 'perfect_end',
      title: 'Ascendant',
      text: "Archbishop Valko's Zulo form collapses, the reshaped flesh softening as Torpor claims him. The hall falls utterly silent. No one has bested Valko in ritual combat in forty years. In this moment, something shifts — you feel the weight of every vampire in the room reconsidering exactly who you are.",
    },
    defeat_easy: {
      type: 'bad_end',
      title: 'Lesson Learned',
      text: "Rodrigo steps back. You're on the ground staring at the warehouse rafters, feeling blood and pride pooling equally. 'Get up,' he says, extending a hand. 'We do this again. And again. Until you're better than me.'",
    },
    defeat_medium: {
      type: 'bad_end',
      title: 'The Pack Wins',
      text: "They don't finish you — this was never about death. Mirka disperses her shadows. Pawel examines his knuckles. Zeta reverts to mostly human shape and walks away without looking back. You lie there and count the damage and wonder which one you'll be able to take in a week's practice.",
    },
    defeat_hard: {
      type: 'dead_end',
      title: 'Into the Long Dark',
      text: "You don't remember falling. You remember Valko's ancient eyes — patient, measuring — and then nothing. You wake on the stone floor alone. Someone has left a note: 'Train. Try again. This is what we are — we do not stop.'",
    },
  },
  scenes: {
    start: {
      act: 1,
      title: 'The Gathering of the Sect',
      narrative: "The warehouse smells of blood and old stone. Fifty vampires of the Sabbat fill the space, their voices a low thrumming chorus. Archbishop Valko stands on a raised platform, his ancient presence filling the room like pressure before a storm.\n\n'Tonight,' he says, 'we hold the Blood Games. Those who wish to prove their worth to the sect will fight. Three trials stand before you — choose the one that fits your ambition.'\n\nA Brujah circles in the center ring, muscles coiled, grinning at you. Three feral vampires crouch near the east wall. Valko himself descends from the platform, cracking his knuckles with a sound like breaking wood.\n\nYou have come here to be tested. Choose your trial.",
      choices: [
        { text: 'Challenge Rodrigo — a single opponent', icon: '⚔', next: 'fight_easy' },
        { text: 'Face the Pack — three opponents at once', icon: '⚔', next: 'fight_medium' },
        { text: 'Challenge Archbishop Valko — the boss trial', icon: '☩', next: 'fight_hard' },
      ],
    },
    fight_easy: {
      act: 2,
      title: "Rodrigo's Challenge",
      narrative: "Rodrigo Vega — twelfth generation Brujah, Priscus of the Chicago pack — steps into the ring. He rolls his neck and it cracks like a gunshot.\n\n'I'll make it quick,' he says. 'For your sake.'\n\nThe ring clears. Valko raises one hand.\n\n'Begin.'",
      combat: {
        label: "Rodrigo's Challenge",
        description: "One-on-one with a seasoned Sabbat Brujah. He fights with Potence and Celerity — fast, hard, unrelenting. Superficial damage only: this is a test, not an execution.",
        enemies: [
          {
            id: 'rodrigo',
            name: 'Rodrigo Vega',
            clan: 'Brujah',
            generation: 12,
            attackPool: 4,
            defensePool: 2,
            maxHealth: 5,
            maxWillpower: 4,
            hunger: 2,
            damageType: 'superficial',
            baseDamage: 0,
            disciplines: { Potence: 1, Celerity: 1 },
            description: 'Priscus of the Chicago pack. Thirty years of street fighting. He prefers brawling to firearms — it feels more honest.',
          },
        ],
        victory_next: 'victory_easy_scene',
        defeat_next: 'defeat_easy_scene',
        flee_next: 'flee_easy_scene',
      },
    },
    fight_medium: {
      act: 2,
      title: 'The Pack Trial',
      narrative: "Three figures move into the ring from different directions. Zeta — Gangrel, already half-shifted, nails like iron spikes. Mirka — Lasombra, shadows pooling at her feet. Pawel — Malkavian, that fractured smile that never quite reaches his eyes.\n\n'Three to one,' someone murmurs. 'Unfair.'\n\nAnother voice: 'That's the point.'\n\nThe three fan out, surrounding you. Zeta snarls. The shadows move.",
      combat: {
        label: 'The Pack Trial',
        description: 'Three Sabbat vampires with different disciplines. Zeta hits hard with aggravated claw damage. Mirka strikes from shadow. Pawel is defensive and difficult to pin down. Manage your targets carefully.',
        enemies: [
          {
            id: 'zeta',
            name: 'Zeta',
            clan: 'Gangrel',
            generation: 11,
            attackPool: 5,
            defensePool: 3,
            maxHealth: 6,
            maxWillpower: 4,
            hunger: 2,
            damageType: 'aggravated',
            baseDamage: 0,
            disciplines: { Protean: 2, Fortitude: 1, Animalism: 1 },
            description: 'Semi-shifted Gangrel. Feral Claws deal aggravated damage. Takes punishment well.',
          },
          {
            id: 'mirka',
            name: 'Mirka',
            clan: 'Lasombra',
            generation: 11,
            attackPool: 4,
            defensePool: 3,
            maxHealth: 5,
            maxWillpower: 5,
            hunger: 1,
            damageType: 'aggravated',
            baseDamage: 0,
            disciplines: { Oblivion: 2, Dominate: 1, Potence: 1 },
            description: 'Shadow attacks bypass light. Fights with patience, waiting for openings.',
          },
          {
            id: 'pawel',
            name: 'Pawel',
            clan: 'Malkavian',
            generation: 12,
            attackPool: 3,
            defensePool: 3,
            maxHealth: 5,
            maxWillpower: 6,
            hunger: 1,
            damageType: 'superficial',
            baseDamage: 0,
            disciplines: { Auspex: 2, Obfuscate: 1, Dominate: 1 },
            description: 'Reads moves before they are made. Unsettling, fractured focus.',
          },
        ],
        victory_next: 'victory_medium_scene',
        defeat_next: 'defeat_medium_scene',
        flee_next: 'flee_medium_scene',
      },
    },
    fight_hard: {
      act: 2,
      title: "The Archbishop's Trial",
      narrative: "Valko steps down from the platform. As he does, his form begins to change.\n\nThe transformation is deliberate — a demonstration of control. His shoulders broaden, spine arching as he grows a full foot taller. His skin takes the texture of scored leather, limbs elongating, jaw distending. The Zulo form — the Tzimisce war-shape — settles over him like a second body.\n\nThe crowd falls back.\n\nHe is seven feet of ancient, reshaped flesh. When he speaks, his voice is barely changed.\n\n'Impress me.'",
      combat: {
        label: "Valko's Trial",
        description: "Archbishop Valko in full Zulo form. Ancient generation, devastating aggravated attacks, natural regeneration every round. This is not a test — this is a crucible. Use every discipline you have.",
        enemies: [
          {
            id: 'valko',
            name: 'Archbishop Valko',
            clan: 'Tzimisce',
            generation: 8,
            attackPool: 8,
            defensePool: 5,
            maxHealth: 10,
            maxWillpower: 8,
            hunger: 1,
            damageType: 'aggravated',
            baseDamage: 1,
            regenPerRound: 1,
            disciplines: { Fortitude: 3, Dominate: 2, Presence: 2 },
            description: 'Archbishop of the Chicago Sabbat. Eight generations from Caine. In Zulo form, his reshaped flesh is a weapon.',
          },
        ],
        victory_next: 'victory_hard_scene',
        defeat_next: 'defeat_hard_scene',
      },
    },
    victory_easy_scene: {
      act: 3,
      title: 'First Blood',
      narrative: "The crowd parts for you as you step from the ring. Rodrigo, sitting up and already knitting, gives you a grudging look.\n\n'You fight well,' he says. 'For now.'\n\nValko watches from the platform, expression unreadable. But he doesn't look away.",
      ending: 'victory_easy',
    },
    victory_medium_scene: {
      act: 3,
      title: 'Above the Pack',
      narrative: "The three of them circle the ring: some limping, some holding wounds that will take nights to close. You stand in the center, blood on your hands, breathing from habit rather than need.\n\nThe warehouse erupts.\n\nValko's thin smile is the only approval that matters here.",
      ending: 'victory_medium',
    },
    victory_hard_scene: {
      act: 3,
      title: 'The New Ascendant',
      narrative: "Valko's Zulo form collapses inward as Torpor takes him, the reshaped flesh softening. He kneels — actually kneels — then topples forward.\n\nNo one speaks.\n\nThen the howling starts.",
      ending: 'victory_hard',
    },
    defeat_easy_scene: {
      act: 3,
      title: 'Lesson Learned',
      narrative: "Rodrigo steps back. You're on the ground, staring at the ceiling, counting what's broken.\n\n'Get up,' he says. 'We do this again. And again.'",
      ending: 'defeat_easy',
    },
    defeat_medium_scene: {
      act: 3,
      title: 'Pack Victorious',
      narrative: "They don't finish you. Mirka disperses her shadows. Pawel tilts his head. Zeta walks away without looking back.\n\nYou lie there and count the damage and begin to make a plan.",
      ending: 'defeat_medium',
    },
    defeat_hard_scene: {
      act: 3,
      title: "The Archbishop's Lesson",
      narrative: "You don't remember falling. You remember Valko's eyes — old, patient, measuring — and then nothing.\n\nYou wake alone. Someone has left a note.\n\n'Train. Try again.'",
      ending: 'defeat_hard',
    },
    flee_easy_scene: {
      act: 2,
      title: 'Walking Away',
      narrative: "You step back out of reach and raise a hand. 'Enough.'\n\nRodrigo stops. Looks at you. Then shrugs.\n\n'Fair enough,' he says. 'Come back when you want to finish it.'\n\nThe crowd murmurs. Not with contempt — with mild, puzzled indifference. You stepped into a sparring match and stepped out. No shame in it. No glory either.",
      ending: 'defeat_easy',
    },
    flee_medium_scene: {
      act: 2,
      title: 'Strategic Retreat',
      narrative: "You break from the encircling pack and make for the warehouse door. Zeta snarls and takes a step — then Mirka puts a hand on her arm. They watch you go.\n\nYou're outside. The Chicago night is cold. The laughter follows you out, low and merciless.\n\nThree opponents. You ran. The Sabbat will remember. So will you.",
      ending: 'defeat_medium',
    },
  },
  locales: {
    hu: {
      title: 'Véres Játékok',
      subtitle: 'A Sabbat Tűzpróbája',
      setting: 'Chicago, 1997',
      acts: {
        1: 'A Vaulderie',
        2: 'Harci Próba',
        3: 'Következmények',
      },
      endings: {
        victory_easy: {
          title: 'Méltónak Bizonyult',
          text: 'Rodrigo összeesik a hideg kövön, letörve, de nem megsemmisítve. A csomag üvölt. Átmentetél az első Vaulderie-próbán — véred összekeveredett az övékkel, értéked megmutatkozott agyarral és ököllel. A Sabbatban a tiszteletet vérrel szerzik. Ma éjjel megszerezted.',
        },
        victory_medium: {
          title: 'A Csomag Felett',
          text: 'Három Sabbat vámpír hever törten körülötted. Az összegyűlt szekta némán néz, majd üvöltésben tör ki. Még Zeta is, félig visszaalakulva, kénytelen vigyorogni a széttört agyarain keresztül. Az érsek egyszer bólint a terem másik végéből. Sabbat vagy.',
        },
        victory_hard: {
          title: 'Fölemelkedett',
          text: 'Valko érsek Zulo-formája összeomlik, az átformált hús megpuhul, ahogy a Torpor befogja. A csarnok teljesen elnémul. Negyven éve nem győzte le senki Valkót rituális harcban. Ebben a pillanatban valami megváltozik — érzed, ahogy a teremben lévő összes vámpír újraértékeli, ki is vagy valójában.',
        },
        defeat_easy: {
          title: 'Tanulság',
          text: "Rodrigo hátrál. A raktár gerendáit bámulod, vért és büszkeséget egyformán érezve a padlón fekve. 'Kelj fel,' mondja, kezet nyújtva. 'Ezt újra megtesszük. Meg újra. Amíg jobb nem leszel nálam.'",
        },
        defeat_medium: {
          title: 'A Csomag Győz',
          text: 'Nem végeznek veled — ez sosem volt halálról szóló. Mirka feloszlatja árnyait. Pawel megvizsgálja a csuklóját. Zeta visszaalakul nagyjából emberivé, és hátranézés nélkül elsétál. Fekszel ott, számolod a sérüléseket, és azon töprengesz, melyiküket győznéd le egy hét edzés után.',
        },
        defeat_hard: {
          title: 'A Hosszú Sötétségbe',
          text: "Nem emlékszel az esésre. Emlékszel Valko ősi szemeire — türelmesek, mérlegelők — aztán semmi. A kőpadlón ébredsz egyedül. Valaki hagyott egy cetlit: 'Edzz. Próbáld újra. Ez az, amik vagyunk — mi nem állunk meg.'",
        },
      },
      scenes: {
        start: {
          title: 'A Szekta Gyülekezete',
          narrative: "A raktár vérre és öreg kőre emlékeztet. Ötven Sabbat vámpír tölti meg a teret, hangjuk mély, zúgó kórust alkot. Valko érsek egy emelvényen áll, ősi jelenléte betölti a termet, mint vihar előtt a nyomás.\n\n'Ma éjjel,' mondja, 'megtartjuk a Véres Játékokat. Akik értéküket bizonyítani akarják a szektának, harcolni fognak. Három próba áll előttetek — válasszátok azt, amelyik illik a becsvágyatokhoz.'\n\nEgy Brujo kering a középső körön, összeszorított izmokkal, vigyorogva rád. Három vad vámpír guggol a keleti falnál. Maga Valko leszáll az emelvényről, feltörve a csuklóját, a hang olyan, mint a reccsenő fa.\n\nIdejöttél, hogy próbára tegyenek. Válassz.",
          choices: [
            'Rodrigo kihívása — egyetlen ellenfél',
            'Szembenézés a Csomaggal — három ellenfél egyszerre',
            'Valko érsek kihívása — a főpróba',
          ],
        },
        fight_easy: {
          title: 'Rodrigo Kihívása',
          narrative: "Rodrigo Vega — tizenkettedik generációs Brujo, a chicagói csomag Priscusa — belép a körbe. Felroppantja a nyakát, és a hang olyan, mint egy pisztolylövés.\n\n'Gyorsan végzünk,' mondja. 'Az érdekedben.'\n\nA kör kiürül. Valko felemeli az egyik kezét.\n\n'Kezdjétek.'",
          combat: {
            label: 'Rodrigo Kihívása',
            description: 'Négyszemközti harc egy tapasztalt Sabbat Brujo-val. Potencia és Gyorsaság kombinációjával harcol — gyors, erős, szüntelen. Csak felszínes sebzés: ez egy próba, nem kivégzés.',
          },
        },
        fight_medium: {
          title: 'A Csomag Próbája',
          narrative: "Három alak lép be a körbe különböző irányokból. Zeta — Gangrel, már félig átalakult, körmei mint vaskampók. Mirka — Lasombra, árnyak gyűlnek a lábai körül. Pawel — Malkáviánus, az a törött mosoly, ami soha nem ér el a szeméig.\n\n'Három az egy ellen,' suttogja valaki. 'Nem fair.'\n\nMásik hang: 'Ez a lényeg.'\n\nA három szétoszlik, körülzárva téged. Zeta morog. Az árnyak megmozdulnak.",
          combat: {
            label: 'A Csomag Próbája',
            description: 'Három különböző diszciplínájú Sabbat vámpír. Zeta karmolásaival súlyos aggravált sebzést oszt. Mirka árnyékból csap le. Pawel védekező és nehéz sarokba szorítani. Gondosan kezeld a célpontokat.',
          },
        },
        fight_hard: {
          title: 'Az Érsek Próbája',
          narrative: "Valko lelép az emelvényről. Ahogy teszi, alakja változni kezd.\n\nAz átalakulás szándékos — az uralom demonstrációja. Vállai kiszélesednek, gerince ívbe hajlik, ahogy egy teljes lábbal megmagasodik. Bőre cserzett bőr állagát veszi fel, végtagjai megnyúlnak, állkapcsa kinyúlik. A Zulo-forma — a Tzimisce háborús-alakja — rátelepül, mint egy második test.\n\nA tömeg hátrálni kezd.\n\nHét láb ősi, átformált hús. Amikor megszólal, hangja alig változott.\n\n'Nyűgözz le.'",
          combat: {
            label: 'Valko Próbája',
            description: 'Valko érsek teljes Zulo-formájában. Ősi generáció, pusztító aggravált támadások, természetes regeneráció minden körben. Ez nem próba — ez a kemence. Használd minden diszciplínádat.',
          },
        },
        victory_easy_scene: {
          title: 'Első Vér',
          narrative: "A tömeg megnyílik előtted, ahogy kilépel a körből. Rodrigo, felülve és már gyógyulva, ellustult pillantást vet rád.\n\n'Jól harcolsz,' mondja. 'Egyelőre.'\n\nValko az emelvényről figyel, kifejezéstelen arccal. De nem néz el.",
        },
        victory_medium_scene: {
          title: 'A Csomag Felett',
          narrative: 'A három körözget a körben: egyik sántít, másik tartja a sebeit, amelyek napokig nem záródnak be. Te állsz a közepén, vérrel a kezeden, megszokásból lélegzel, szükség nélkül.\n\nA raktár felrobban.\n\nValko vékony mosolya az egyetlen elismerés, ami számít.',
        },
        victory_hard_scene: {
          title: 'Az Új Felemelkedő',
          narrative: 'Valko Zulo-formája összeomlik belülről, ahogy a Torpor befogja, az átformált hús megpuhul. Térdel — valójában térdel — aztán előre esik.\n\nSenki sem szól.\n\nAztán megkezdődik az üvöltés.',
        },
        defeat_easy_scene: {
          title: 'Tanulság',
          narrative: "Rodrigo hátrál. A padlón fekszel, a plafont bámulod, számolva, mi tört el.\n\n'Kelj fel,' mondja. 'Ezt újra megtesszük. Meg újra.'",
        },
        defeat_medium_scene: {
          title: 'A Csomag Győz',
          narrative: 'Nem végeznek veled. Mirka feloszlatja árnyait. Pawel oldalra billenti fejét. Zeta hátranézés nélkül elsétál.\n\nFekszel ott, számolod a sérüléseket, és tervet szövögetsz.',
        },
        defeat_hard_scene: {
          title: 'Az Érsek Leckéje',
          narrative: "Nem emlékszel az esésre. Emlékszel Valko szemére — öreg, türelmes, mérlegelő — aztán semmi.\n\nA kőpadlón ébredsz egyedül. Valaki hagyott egy cetlit.\n\n'Edzz. Próbáld újra.'",
        },
        flee_easy_scene: {
          title: 'Elvonulás',
          narrative: "Visszalépel a hatótávolságon kívülre, és felemeled a kezed. 'Elég.'\n\nRodrigo megáll. Rád néz. Aztán megvon egyet.\n\n'Ahogy gondolod,' mondja. 'Gyere vissza, ha be akarod fejezni.'\n\nA tömeg morog. Nem megvetéssel — enyhe, zavarba ejtő közönnyel. Beléptél egy sparringba, és kiléptél. Nincs ebben szégyen. Dicsőség sem.",
        },
        flee_medium_scene: {
          title: 'Taktikai Visszavonulás',
          narrative: 'Kitörsz a körülzáró csomag gyűrűjéből, és a raktárajtó felé tartasz. Zeta morog és tesz egy lépést — aztán Mirka ráteszi a kezét a karjára. Nézik, ahogy mész.\n\nOdakint vagy. A chicagói éjszaka hideg. A nevetés követ ki, halk és kíméletlen.\n\nHárom ellenfél. Elmenekültél. A Sabbat emlékezni fog. Te is.',
        },
      },
    },
  },
};
